'use client';

import { useState, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Scissors } from 'lucide-react';
import toast from 'react-hot-toast';
import { destroySession } from '@/app/actions/auth';
import {
  consumeRecoveryToken,
  lookupUserKindByEmail,
} from '@/app/actions/auth-credentials';
import { useAppStore } from '@/store/app-store';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  getPasswordError,
  getAgentPasswordError,
  AGENT_MIN_PASSWORD_LENGTH,
} from '@/lib/schemas/common';

// The reset link generated by authAdmin.generateLink({type:'recovery'}) is:
//   https://icut.pk/reset-password?token=ABCDEF&email=...&type=recovery
// (Replaces the previous Supabase URL-fragment recovery flow.)

function ResetPasswordInner() {
  const router = useRouter();
  const params = useSearchParams();
  const token = params.get('token') ?? '';
  const email = params.get('email') ?? '';

  const [ready, setReady] = useState(false);
  const [validLink, setValidLink] = useState(false);
  const [isAgent, setIsAgent] = useState(false);
  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (!token || !email) {
      setReady(true);
      return;
    }
    void (async () => {
      // We don't pre-validate the token (would burn it). Just check the email
      // exists + figure out which password rules to apply, then trust the
      // server-side validation that runs at submit.
      const kind = await lookupUserKindByEmail(email);
      if (kind.kind === 'unknown') {
        setValidLink(false);
      } else {
        setValidLink(true);
        setIsAgent(kind.kind === 'sales_agent');
      }
      setReady(true);
    })();
  }, [token, email]);

  const validate = isAgent ? getAgentPasswordError : getPasswordError;

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const pwErr = validate(password);
    if (pwErr) {
      toast.error(pwErr);
      return;
    }
    if (password !== confirm) {
      toast.error('Passwords do not match');
      return;
    }
    setSaving(true);
    try {
      const { error } = await consumeRecoveryToken({ email, token, newPassword: password });
      if (error) throw new Error(error.message);
      // Clear any iCut session that might be lingering — the user who
      // triggered the reset link could be a different identity in this
      // browser (e.g. a super_admin who just created the agent).
      await destroySession().catch(() => {});
      useAppStore.getState().reset();
      toast.success('Password updated — please log in with your new password');
      window.location.href = '/login';
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to update password');
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center p-6 bg-background">
      <div className="w-full max-w-md">
        <div className="flex items-center gap-2 mb-8 justify-center">
          <Scissors className="w-8 h-8 text-gold" />
          <h1 className="font-heading text-3xl font-bold">iCut</h1>
        </div>

        {!ready ? (
          <div className="text-center text-muted-foreground text-sm">Checking reset link…</div>
        ) : !validLink ? (
          <div className="text-center space-y-4">
            <h2 className="font-heading text-xl font-bold">Reset link expired</h2>
            <p className="text-sm text-muted-foreground">
              This password reset link is invalid or has expired. Request a new one from the login page.
            </p>
            <Button onClick={() => router.push('/login')} className="bg-gold hover:bg-gold/90 text-black font-bold">
              Back to login
            </Button>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-4">
            <h2 className="font-heading text-xl font-bold text-center">Set a new password</h2>
            <div>
              <Label htmlFor="password">New password</Label>
              <Input
                id="password"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                minLength={isAgent ? AGENT_MIN_PASSWORD_LENGTH : 10}
                required
                className="mt-1.5"
                placeholder={isAgent ? `Min ${AGENT_MIN_PASSWORD_LENGTH} characters` : 'Min 10 characters'}
              />
            </div>
            <div>
              <Label htmlFor="confirm">Confirm password</Label>
              <Input
                id="confirm"
                type="password"
                value={confirm}
                onChange={(e) => setConfirm(e.target.value)}
                minLength={isAgent ? AGENT_MIN_PASSWORD_LENGTH : 8}
                required
                className="mt-1.5"
              />
              <p className="text-xs text-muted-foreground mt-1">
                {isAgent
                  ? `Min ${AGENT_MIN_PASSWORD_LENGTH} characters. Keep it simple and easy to remember.`
                  : 'Min 8 characters, with an uppercase letter, a number, and a special character.'}
              </p>
              {password && confirm && password !== confirm && (
                <p className="text-xs text-destructive mt-1">Passwords do not match</p>
              )}
            </div>
            <Button
              type="submit"
              disabled={saving || !!validate(password) || password !== confirm}
              className="w-full bg-gold hover:bg-gold/90 text-black font-bold"
            >
              {saving ? 'Updating…' : 'Update password'}
            </Button>
          </form>
        )}
      </div>
    </div>
  );
}

export default function ResetPasswordPage() {
  // useSearchParams requires a Suspense boundary in App Router.
  return (
    <Suspense fallback={null}>
      <ResetPasswordInner />
    </Suspense>
  );
}
