/**
 * City metadata for programmatic SEO pages. Each row feeds
 * `src/lib/seo/page-content.ts` to produce meaningfully distinct copy per
 * city instead of templated near-duplicates (which Google penalises as
 * "doorway pages").
 *
 * Population + market-size figures are order-of-magnitude estimates drawn
 * from public census + commercial listings — accurate enough to colour the
 * page, not precise enough to quote as statistics. If you ever want to
 * tighten them, swap to data-driven sources and rebuild.
 */

export interface CityRecord {
  slug: string;               // url segment
  city: string;               // display name
  country: 'PK' | 'AE' | 'SA' | 'QA' | 'KW' | 'BH' | 'OM';
  countryName: string;
  region: string;             // province / emirate / governorate
  currency: 'PKR' | 'AED' | 'SAR' | 'QAR' | 'KWD' | 'BHD' | 'OMR';
  currencySymbol: string;
  population: string;         // e.g. "16 million", "300,000"
  salonCount: string;         // e.g. "~8,000 salons & barbershops"
  languages: string[];
  paymentMethods: string[];   // local rails (JazzCash, ApplePay, etc.)
  peakHours: string;          // busiest hours locally
  context: string;            // 1-2 sentences of local colour
  priceTier: 'value' | 'mid' | 'premium';  // signals typical ticket size
}

// ────────────────────────────────────────────────────────────────────────
// Pakistan — 60 cities
// ────────────────────────────────────────────────────────────────────────

export const PAKISTAN_CITIES: CityRecord[] = [
  { slug: 'karachi',       city: 'Karachi',       country: 'PK', countryName: 'Pakistan', region: 'Sindh',            currency: 'PKR', currencySymbol: 'Rs', population: '16 million', salonCount: '~8,000 salons & barbershops', languages: ['Urdu', 'English', 'Sindhi'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Raast', 'Card', 'Cash'], peakHours: '4 PM – 10 PM', context: 'Pakistan\u2019s largest market for beauty services, with a concentration of premium spas in DHA, Clifton and Bahria Town, plus tens of thousands of neighbourhood barbershops across the city.', priceTier: 'mid' },
  { slug: 'lahore',        city: 'Lahore',        country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '13 million', salonCount: '~6,500 salons & parlors', languages: ['Urdu', 'Punjabi', 'English'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Raast', 'Card', 'Cash'], peakHours: '5 PM – 11 PM', context: 'Cultural capital with an intensely bridal-season-driven salon economy \u2014 DHA, Gulberg and Johar Town see booking surges through wedding months.', priceTier: 'mid' },
  { slug: 'islamabad',     city: 'Islamabad',     country: 'PK', countryName: 'Pakistan', region: 'ICT',              currency: 'PKR', currencySymbol: 'Rs', population: '1.2 million',  salonCount: '~1,200 salons', languages: ['Urdu', 'English'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Raast', 'Card'], peakHours: '4 PM – 9 PM', context: 'Diplomatic corridor and corporate-expat clientele push premium salons in F-6, F-7 and E-11 toward spa-grade pricing and card-first billing.', priceTier: 'premium' },
  { slug: 'rawalpindi',    city: 'Rawalpindi',    country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '2.3 million', salonCount: '~2,100 salons', languages: ['Urdu', 'Punjabi'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 10 PM', context: 'Twin-city of Islamabad with a far more price-sensitive salon market; Saddar, Raja Bazaar and Westridge dominate foot traffic.', priceTier: 'value' },
  { slug: 'faisalabad',    city: 'Faisalabad',    country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '3.2 million', salonCount: '~3,400 salons', languages: ['Urdu', 'Punjabi'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 10 PM', context: 'Textile hub with strong mid-market bridal demand; Clock Tower and Peoples Colony absorb most walk-in volume.', priceTier: 'mid' },
  { slug: 'multan',        city: 'Multan',        country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '2.0 million', salonCount: '~1,900 salons', languages: ['Urdu', 'Saraiki', 'Punjabi'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '6 PM – 10 PM', context: 'Southern Punjab commercial hub with a surge of new ladies-only parlors through Cantt and Model Town as disposable income grows.', priceTier: 'mid' },
  { slug: 'peshawar',      city: 'Peshawar',      country: 'PK', countryName: 'Pakistan', region: 'KP',               currency: 'PKR', currencySymbol: 'Rs', population: '2.1 million', salonCount: '~1,700 barbershops & salons', languages: ['Pashto', 'Urdu', 'Hindko'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Barbershop-heavy market; tip-dominant tipping culture and long loyalty cycles reward staff-level reporting.', priceTier: 'value' },
  { slug: 'quetta',        city: 'Quetta',        country: 'PK', countryName: 'Pakistan', region: 'Balochistan',      currency: 'PKR', currencySymbol: 'Rs', population: '1.0 million', salonCount: '~600 salons', languages: ['Urdu', 'Pashto', 'Balochi'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '4 PM – 9 PM', context: 'Compact provincial capital where same-staff loyalty and seasonal pricing matter more than chain branding.', priceTier: 'value' },
  { slug: 'hyderabad',     city: 'Hyderabad',     country: 'PK', countryName: 'Pakistan', region: 'Sindh',            currency: 'PKR', currencySymbol: 'Rs', population: '1.7 million', salonCount: '~1,400 salons', languages: ['Sindhi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 10 PM', context: 'Growing ladies-parlor corridor along Auto Bhan and Latifabad, with Karachi owners opening second branches.', priceTier: 'mid' },
  { slug: 'gujranwala',    city: 'Gujranwala',    country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '2.0 million', salonCount: '~1,800 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 10 PM', context: 'Industrial city with dense barbershop density and a growing wedding-season bridal package market.', priceTier: 'value' },
  { slug: 'sialkot',       city: 'Sialkot',       country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '700,000',     salonCount: '~800 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '6 PM – 10 PM', context: 'Export-economy city with strong overseas-remittance household budgets; bridal spending is higher than population would suggest.', priceTier: 'mid' },
  { slug: 'bahawalpur',    city: 'Bahawalpur',    country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '760,000',     salonCount: '~600 salons', languages: ['Saraiki', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '6 PM – 10 PM', context: 'Regional education + hospital hub; weekend foot-traffic skews heavily to students and junior-professionals.', priceTier: 'value' },
  { slug: 'sargodha',      city: 'Sargodha',      country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '660,000',     salonCount: '~500 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Mid-size Punjabi city with citrus-belt prosperity and a steady local bridal circuit.', priceTier: 'value' },
  { slug: 'sukkur',        city: 'Sukkur',        country: 'PK', countryName: 'Pakistan', region: 'Sindh',            currency: 'PKR', currencySymbol: 'Rs', population: '500,000',     salonCount: '~400 salons', languages: ['Sindhi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Riverside commercial centre with strong regional footfall during Eid and wedding season.', priceTier: 'value' },
  { slug: 'larkana',       city: 'Larkana',       country: 'PK', countryName: 'Pakistan', region: 'Sindh',            currency: 'PKR', currencySymbol: 'Rs', population: '490,000',     salonCount: '~350 salons', languages: ['Sindhi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Agriculturally anchored local economy with neighbourhood-first salon culture.', priceTier: 'value' },
  { slug: 'sheikhupura',   city: 'Sheikhupura',   country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '470,000',     salonCount: '~400 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Lahore satellite with spillover bridal bookings through the wedding months.', priceTier: 'value' },
  { slug: 'rahim-yar-khan',city: 'Rahim Yar Khan',country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '420,000',     salonCount: '~350 salons', languages: ['Saraiki', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Cross-border trade corridor city with a mix of working-class and farm-landlord clientele.', priceTier: 'value' },
  { slug: 'jhang',         city: 'Jhang',         country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '420,000',     salonCount: '~300 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Traditional Punjabi city where family-owned salons dominate and trust is earned through decades of the same chair.', priceTier: 'value' },
  { slug: 'gujrat',        city: 'Gujrat',        country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '390,000',     salonCount: '~350 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Overseas-remittance stronghold; household beauty spending punches above city size.', priceTier: 'mid' },
  { slug: 'mardan',        city: 'Mardan',        country: 'PK', countryName: 'Pakistan', region: 'KP',               currency: 'PKR', currencySymbol: 'Rs', population: '360,000',     salonCount: '~300 barbershops & salons', languages: ['Pashto', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Barbershop-first market with strong walk-in culture; cash still leads by ticket volume.', priceTier: 'value' },
  { slug: 'kasur',         city: 'Kasur',         country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '360,000',     salonCount: '~250 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Lahore satellite with a tannery-belt economy and deeply local salon patronage patterns.', priceTier: 'value' },
  { slug: 'dera-ghazi-khan',city: 'Dera Ghazi Khan',country:'PK',countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '340,000',     salonCount: '~280 salons', languages: ['Saraiki', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Gateway to South Punjab with a steady locally-anchored salon base.', priceTier: 'value' },
  { slug: 'sahiwal',       city: 'Sahiwal',       country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '390,000',     salonCount: '~320 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Agricultural mid-belt with rising ladies-parlor investments along College Road and Farid Town.', priceTier: 'value' },
  { slug: 'nawabshah',     city: 'Nawabshah',     country: 'PK', countryName: 'Pakistan', region: 'Sindh',            currency: 'PKR', currencySymbol: 'Rs', population: '280,000',     salonCount: '~220 salons', languages: ['Sindhi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Canal-fed Sindh district with a local-first salon scene and weddings anchoring the calendar.', priceTier: 'value' },
  { slug: 'mingora',       city: 'Mingora',       country: 'PK', countryName: 'Pakistan', region: 'KP',               currency: 'PKR', currencySymbol: 'Rs', population: '330,000',     salonCount: '~250 salons', languages: ['Pashto', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '4 PM – 8 PM', context: 'Swat Valley commercial core; tourism-season spikes drive barbershop volume.', priceTier: 'value' },
  { slug: 'okara',         city: 'Okara',         country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '300,000',     salonCount: '~260 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Military + agricultural mix; cantonment areas see disproportionate card usage.', priceTier: 'value' },
  { slug: 'burewala',      city: 'Burewala',      country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '230,000',     salonCount: '~180 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Vehari district hub with a tight local supply chain and cash-dominant flow.', priceTier: 'value' },
  { slug: 'jacobabad',     city: 'Jacobabad',     country: 'PK', countryName: 'Pakistan', region: 'Sindh',            currency: 'PKR', currencySymbol: 'Rs', population: '220,000',     salonCount: '~150 salons', languages: ['Sindhi', 'Balochi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '4 PM – 8 PM', context: 'Northern Sindh hub near the Balochistan border; low-cost barbershops dominate.', priceTier: 'value' },
  { slug: 'muzaffargarh',  city: 'Muzaffargarh',  country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '300,000',     salonCount: '~240 salons', languages: ['Saraiki', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Thermal-belt city with a strong neighbourhood-salon culture.', priceTier: 'value' },
  { slug: 'abbottabad',    city: 'Abbottabad',    country: 'PK', countryName: 'Pakistan', region: 'KP',               currency: 'PKR', currencySymbol: 'Rs', population: '210,000',     salonCount: '~250 salons', languages: ['Hindko', 'Urdu', 'English'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Card', 'Cash'], peakHours: '4 PM – 9 PM', context: 'Education hub with a concentration of ladies parlors serving college and boarding-school populations year-round.', priceTier: 'mid' },
  { slug: 'turbat',        city: 'Turbat',        country: 'PK', countryName: 'Pakistan', region: 'Balochistan',      currency: 'PKR', currencySymbol: 'Rs', population: '220,000',     salonCount: '~130 salons', languages: ['Balochi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '4 PM – 8 PM', context: 'Makran coastal commercial hub with a modest but growing barbershop tier.', priceTier: 'value' },
  { slug: 'dera-ismail-khan',city: 'Dera Ismail Khan',country: 'PK',countryName: 'Pakistan', region: 'KP',             currency: 'PKR', currencySymbol: 'Rs', population: '220,000',     salonCount: '~170 salons', languages: ['Saraiki', 'Pashto', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '4 PM – 8 PM', context: 'Historic garrison city bridging KP and South Punjab; barbershop traffic peaks around Friday prayers.', priceTier: 'value' },
  { slug: 'khanpur',       city: 'Khanpur',       country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '200,000',     salonCount: '~150 salons', languages: ['Saraiki', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Southern Punjab sub-district; reputation travels through word-of-mouth faster than any advertising channel.', priceTier: 'value' },
  { slug: 'khairpur',      city: 'Khairpur',      country: 'PK', countryName: 'Pakistan', region: 'Sindh',            currency: 'PKR', currencySymbol: 'Rs', population: '200,000',     salonCount: '~140 salons', languages: ['Sindhi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Mir-family heartland with a date-farming local economy and deeply traditional bridal rituals.', priceTier: 'value' },
  { slug: 'chiniot',       city: 'Chiniot',       country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '240,000',     salonCount: '~180 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Furniture-trade city with a business-family clientele and premium bridal pricing relative to population.', priceTier: 'mid' },
  { slug: 'daska',         city: 'Daska',         country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '190,000',     salonCount: '~140 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Sialkot adjacent town with a local-first salon market and heavy Eid bridal bookings.', priceTier: 'value' },
  { slug: 'hafizabad',     city: 'Hafizabad',     country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '180,000',     salonCount: '~120 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Rice-belt town; weddings happen in waves through the cooler months.', priceTier: 'value' },
  { slug: 'sadiqabad',     city: 'Sadiqabad',     country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '230,000',     salonCount: '~170 salons', languages: ['Saraiki', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Rahim Yar Khan adjacent commercial centre; salon owners often run multiple shops across Sadiqabad + Khanpur.', priceTier: 'value' },
  { slug: 'mirpur-khas',   city: 'Mirpur Khas',   country: 'PK', countryName: 'Pakistan', region: 'Sindh',            currency: 'PKR', currencySymbol: 'Rs', population: '240,000',     salonCount: '~170 salons', languages: ['Sindhi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Mango-country hub with a deeply Sindhi bridal aesthetic and steady parlor demand.', priceTier: 'value' },
  { slug: 'kamalia',       city: 'Kamalia',       country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '140,000',     salonCount: '~100 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Textile town with a small but loyal salon economy; same-chair relationships often span a decade.', priceTier: 'value' },
  { slug: 'jhelum',        city: 'Jhelum',        country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '230,000',     salonCount: '~200 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Card', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Heavy overseas-remittance market with disproportionate bridal and groom-prep spending.', priceTier: 'mid' },
  { slug: 'wazirabad',     city: 'Wazirabad',     country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '180,000',     salonCount: '~130 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Cutlery-export town with a tight local trust network; reputation is everything.', priceTier: 'value' },
  { slug: 'kot-addu',      city: 'Kot Addu',      country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '140,000',     salonCount: '~90 salons', languages: ['Saraiki', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Power-plant adjacent town; payroll cycles drive booking patterns more than holidays.', priceTier: 'value' },
  { slug: 'charsadda',     city: 'Charsadda',     country: 'PK', countryName: 'Pakistan', region: 'KP',               currency: 'PKR', currencySymbol: 'Rs', population: '160,000',     salonCount: '~110 barbershops & salons', languages: ['Pashto', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '4 PM – 8 PM', context: 'Peshawar adjacent barbershop-dense market with walk-in volume as the lifeblood.', priceTier: 'value' },
  { slug: 'pakpattan',     city: 'Pakpattan',     country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '180,000',     salonCount: '~130 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Historic shrine city; salons see influx during Urs and the wedding months.', priceTier: 'value' },
  { slug: 'kamoke',        city: 'Kamoke',        country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '250,000',     salonCount: '~190 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Gujranwala adjacent town; industrial-estate payroll cycles move demand.', priceTier: 'value' },
  { slug: 'gojra',         city: 'Gojra',         country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '180,000',     salonCount: '~130 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Toba Tek Singh district hub; rice-and-citrus belt salons cluster around Bazaar Road.', priceTier: 'value' },
  { slug: 'layyah',        city: 'Layyah',        country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '160,000',     salonCount: '~110 salons', languages: ['Saraiki', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Desert-adjacent local economy with steady bridal demand across tribes.', priceTier: 'value' },
  { slug: 'tando-allahyar',city: 'Tando Allahyar', country: 'PK',countryName: 'Pakistan', region: 'Sindh',            currency: 'PKR', currencySymbol: 'Rs', population: '170,000',     salonCount: '~120 salons', languages: ['Sindhi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Sugar-mill town with a local-first salon scene and tight chair loyalty.', priceTier: 'value' },
  { slug: 'bhakkar',       city: 'Bhakkar',       country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '140,000',     salonCount: '~100 salons', languages: ['Saraiki', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Thal-desert town; demand is steady through the year with spikes around harvest.', priceTier: 'value' },
  { slug: 'chakwal',       city: 'Chakwal',       country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '160,000',     salonCount: '~120 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Potohar plateau town with strong overseas-remittance spending on wedding prep.', priceTier: 'mid' },
  { slug: 'dadu',          city: 'Dadu',          country: 'PK', countryName: 'Pakistan', region: 'Sindh',            currency: 'PKR', currencySymbol: 'Rs', population: '130,000',     salonCount: '~90 salons', languages: ['Sindhi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Indus-belt town with slow-but-steady bridal demand year-round.', priceTier: 'value' },
  { slug: 'haroonabad',    city: 'Haroonabad',    country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '140,000',     salonCount: '~100 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Bahawalnagar district town; salon traffic peaks around monthly payday.', priceTier: 'value' },
  { slug: 'khushab',       city: 'Khushab',       country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '130,000',     salonCount: '~90 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Salt-range town with modest disposable income and loyal repeat clients.', priceTier: 'value' },
  { slug: 'mandi-bahauddin',city: 'Mandi Bahauddin',country: 'PK',countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '170,000',     salonCount: '~130 salons', languages: ['Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Gujrat neighbour; Gulf-remittance flows support mid-tier bridal pricing.', priceTier: 'mid' },
  { slug: 'nowshera',      city: 'Nowshera',      country: 'PK', countryName: 'Pakistan', region: 'KP',               currency: 'PKR', currencySymbol: 'Rs', population: '160,000',     salonCount: '~110 barbershops & salons', languages: ['Pashto', 'Hindko', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '4 PM – 8 PM', context: 'Military city with cantonment-adjacent salons catering to steady payroll-backed demand.', priceTier: 'value' },
  { slug: 'swabi',         city: 'Swabi',         country: 'PK', countryName: 'Pakistan', region: 'KP',               currency: 'PKR', currencySymbol: 'Rs', population: '170,000',     salonCount: '~120 salons', languages: ['Pashto', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '4 PM – 8 PM', context: 'Gandhara-belt city; tourism plus local weddings drive barbershop peak hours.', priceTier: 'value' },
  { slug: 'tando-adam',    city: 'Tando Adam',    country: 'PK', countryName: 'Pakistan', region: 'Sindh',            currency: 'PKR', currencySymbol: 'Rs', population: '140,000',     salonCount: '~100 salons', languages: ['Sindhi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Agricultural Sindh hub; traditional bridal rituals keep parlors busy through the cooler months.', priceTier: 'value' },
  { slug: 'vehari',        city: 'Vehari',        country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '150,000',     salonCount: '~110 salons', languages: ['Punjabi', 'Saraiki', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Cotton-belt district town; burewala + vehari salons often share stylists across both markets.', priceTier: 'value' },
  { slug: 'ahmedpur-east', city: 'Ahmedpur East', country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '130,000',     salonCount: '~90 salons', languages: ['Saraiki', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Bahawalpur adjacent small city; Nawab-era bridal traditions still drive high-ticket seasonal spending.', priceTier: 'value' },
  { slug: 'mianwali',      city: 'Mianwali',      country: 'PK', countryName: 'Pakistan', region: 'Punjab',           currency: 'PKR', currencySymbol: 'Rs', population: '130,000',     salonCount: '~100 salons', languages: ['Saraiki', 'Punjabi', 'Urdu'], paymentMethods: ['JazzCash', 'EasyPaisa', 'Cash'], peakHours: '5 PM – 9 PM', context: 'Indus-bend town with long-memory salon loyalty and healthy barbershop density.', priceTier: 'value' },
];

// ────────────────────────────────────────────────────────────────────────
// Gulf — 40 cities
// ────────────────────────────────────────────────────────────────────────

export const GULF_CITIES: CityRecord[] = [
  // UAE — 8
  { slug: 'dubai',             city: 'Dubai',           country: 'AE', countryName: 'UAE',          region: 'Dubai',          currency: 'AED', currencySymbol: 'AED', population: '3.6 million', salonCount: '~3,200 licensed salons', languages: ['Arabic', 'English', 'Urdu', 'Hindi'], paymentMethods: ['Apple Pay', 'Card', 'Samsung Pay', 'Cash'], peakHours: '12 PM – 11 PM', context: 'Licensed-professional-only market with tight DED + health authority rules; ladies salons operate as fully enclosed rooms. Average ticket runs AED 150\u2013600 for services.', priceTier: 'premium' },
  { slug: 'abu-dhabi',         city: 'Abu Dhabi',       country: 'AE', countryName: 'UAE',          region: 'Abu Dhabi',      currency: 'AED', currencySymbol: 'AED', population: '1.5 million', salonCount: '~1,400 licensed salons', languages: ['Arabic', 'English', 'Urdu'], paymentMethods: ['Apple Pay', 'Card', 'Cash'], peakHours: '2 PM – 11 PM', context: 'Government capital with a heavier mix of hotel-attached spas and ladies-only beauty centres in Khalidiya and Al Reem.', priceTier: 'premium' },
  { slug: 'sharjah',           city: 'Sharjah',         country: 'AE', countryName: 'UAE',          region: 'Sharjah',        currency: 'AED', currencySymbol: 'AED', population: '1.8 million', salonCount: '~1,500 licensed salons', languages: ['Arabic', 'English', 'Urdu'], paymentMethods: ['Apple Pay', 'Card', 'Cash'], peakHours: '2 PM – 10 PM', context: 'Family-oriented emirate with strict modesty norms; ladies salons dominate, and bridal packages often run AED 2,500+.', priceTier: 'mid' },
  { slug: 'ajman',             city: 'Ajman',           country: 'AE', countryName: 'UAE',          region: 'Ajman',          currency: 'AED', currencySymbol: 'AED', population: '540,000',     salonCount: '~500 licensed salons', languages: ['Arabic', 'English', 'Urdu'], paymentMethods: ['Apple Pay', 'Card', 'Cash'], peakHours: '2 PM – 10 PM', context: 'Value-tier emirate adjacent to Sharjah; working-class-led market with solid subcontinental salon presence.', priceTier: 'mid' },
  { slug: 'fujairah',          city: 'Fujairah',        country: 'AE', countryName: 'UAE',          region: 'Fujairah',       currency: 'AED', currencySymbol: 'AED', population: '260,000',     salonCount: '~220 licensed salons', languages: ['Arabic', 'English', 'Urdu'], paymentMethods: ['Card', 'Apple Pay', 'Cash'], peakHours: '3 PM – 10 PM', context: 'East-coast mountain-and-beach emirate with a smaller but steady salon economy and weekend tourist spikes.', priceTier: 'mid' },
  { slug: 'ras-al-khaimah',    city: 'Ras Al Khaimah',  country: 'AE', countryName: 'UAE',          region: 'Ras Al Khaimah', currency: 'AED', currencySymbol: 'AED', population: '350,000',     salonCount: '~300 licensed salons', languages: ['Arabic', 'English', 'Urdu'], paymentMethods: ['Card', 'Apple Pay', 'Cash'], peakHours: '2 PM – 10 PM', context: 'Fast-growing emirate; hospitality-driven demand plus family-centre salons dominate the market.', priceTier: 'mid' },
  { slug: 'umm-al-quwain',     city: 'Umm Al Quwain',   country: 'AE', countryName: 'UAE',          region: 'Umm Al Quwain',  currency: 'AED', currencySymbol: 'AED', population: '80,000',      salonCount: '~90 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['Card', 'Apple Pay', 'Cash'], peakHours: '3 PM – 9 PM', context: 'Smallest emirate by population; tight-knit salon community with steady local regulars.', priceTier: 'mid' },
  { slug: 'al-ain',            city: 'Al Ain',          country: 'AE', countryName: 'UAE',          region: 'Abu Dhabi',      currency: 'AED', currencySymbol: 'AED', population: '770,000',     salonCount: '~600 licensed salons', languages: ['Arabic', 'English', 'Urdu'], paymentMethods: ['Card', 'Apple Pay', 'Cash'], peakHours: '2 PM – 10 PM', context: 'Garden-oasis city; Emirati-family weddings run large and long, with packages often booked months out.', priceTier: 'premium' },
  // Saudi Arabia — 16
  { slug: 'riyadh',            city: 'Riyadh',          country: 'SA', countryName: 'Saudi Arabia', region: 'Riyadh',         currency: 'SAR', currencySymbol: 'SAR', population: '7.6 million', salonCount: '~5,500 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['Apple Pay', 'mada', 'STC Pay', 'Card'], peakHours: '4 PM – 12 AM', context: 'Largest salon market in the Kingdom; Saudi-female-owned ladies salons are growing rapidly under Vision 2030 reforms.', priceTier: 'premium' },
  { slug: 'jeddah',            city: 'Jeddah',          country: 'SA', countryName: 'Saudi Arabia', region: 'Makkah',         currency: 'SAR', currencySymbol: 'SAR', population: '4.7 million', salonCount: '~4,000 licensed salons', languages: ['Arabic', 'English', 'Urdu'], paymentMethods: ['Apple Pay', 'mada', 'STC Pay', 'Card'], peakHours: '5 PM – 12 AM', context: 'Red Sea commercial capital; beach-weekend weddings plus Hajj-season tourism drive peak-season pricing.', priceTier: 'premium' },
  { slug: 'mecca',             city: 'Mecca',           country: 'SA', countryName: 'Saudi Arabia', region: 'Makkah',         currency: 'SAR', currencySymbol: 'SAR', population: '2.0 million', salonCount: '~1,400 licensed salons', languages: ['Arabic', 'Urdu', 'English'], paymentMethods: ['Apple Pay', 'mada', 'Card'], peakHours: '4 PM – 11 PM', context: 'Pilgrimage-driven demand with Ramadan and Hajj as peak salon seasons; ladies parlors cluster near residential districts.', priceTier: 'mid' },
  { slug: 'medina',            city: 'Medina',          country: 'SA', countryName: 'Saudi Arabia', region: 'Madinah',        currency: 'SAR', currencySymbol: 'SAR', population: '1.5 million', salonCount: '~1,100 licensed salons', languages: ['Arabic', 'Urdu'], paymentMethods: ['Apple Pay', 'mada', 'Card'], peakHours: '4 PM – 11 PM', context: 'Second holy city; salon volume mirrors pilgrim arrivals with a steady local baseline year-round.', priceTier: 'mid' },
  { slug: 'dammam',            city: 'Dammam',          country: 'SA', countryName: 'Saudi Arabia', region: 'Eastern Province',currency: 'SAR', currencySymbol: 'SAR', population: '1.1 million', salonCount: '~900 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['Apple Pay', 'mada', 'STC Pay', 'Card'], peakHours: '4 PM – 12 AM', context: 'Oil-industry capital; expat clientele plus rising Saudi-female ownership of ladies salons.', priceTier: 'premium' },
  { slug: 'khobar',            city: 'Khobar',          country: 'SA', countryName: 'Saudi Arabia', region: 'Eastern Province',currency: 'SAR', currencySymbol: 'SAR', population: '620,000',     salonCount: '~700 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['Apple Pay', 'mada', 'STC Pay', 'Card'], peakHours: '4 PM – 12 AM', context: 'Corniche city with dense premium salon corridor along Prince Turki Road.', priceTier: 'premium' },
  { slug: 'tabuk',             city: 'Tabuk',           country: 'SA', countryName: 'Saudi Arabia', region: 'Tabuk',          currency: 'SAR', currencySymbol: 'SAR', population: '670,000',     salonCount: '~500 licensed salons', languages: ['Arabic'], paymentMethods: ['mada', 'Apple Pay', 'Card'], peakHours: '4 PM – 11 PM', context: 'Northwestern regional capital; NEOM-adjacent development is quietly lifting premium-tier demand.', priceTier: 'mid' },
  { slug: 'abha',              city: 'Abha',            country: 'SA', countryName: 'Saudi Arabia', region: 'Asir',           currency: 'SAR', currencySymbol: 'SAR', population: '370,000',     salonCount: '~300 licensed salons', languages: ['Arabic'], paymentMethods: ['mada', 'Apple Pay', 'Card'], peakHours: '4 PM – 11 PM', context: 'Highland tourist city; summer-season flight-of-GCC-tourists drives salon bookings significantly.', priceTier: 'mid' },
  { slug: 'taif',              city: 'Taif',            country: 'SA', countryName: 'Saudi Arabia', region: 'Makkah',         currency: 'SAR', currencySymbol: 'SAR', population: '690,000',     salonCount: '~550 licensed salons', languages: ['Arabic'], paymentMethods: ['mada', 'Apple Pay', 'Card'], peakHours: '4 PM – 11 PM', context: 'Highland summer capital; wedding-season volume stretches longer than lowland cities.', priceTier: 'mid' },
  { slug: 'yanbu',             city: 'Yanbu',           country: 'SA', countryName: 'Saudi Arabia', region: 'Madinah',        currency: 'SAR', currencySymbol: 'SAR', population: '330,000',     salonCount: '~280 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['mada', 'Apple Pay', 'Card'], peakHours: '4 PM – 11 PM', context: 'Industrial port city; petrochemical-worker expat clientele plus local Saudi-family demand.', priceTier: 'mid' },
  { slug: 'buraydah',          city: 'Buraydah',        country: 'SA', countryName: 'Saudi Arabia', region: 'Qassim',         currency: 'SAR', currencySymbol: 'SAR', population: '610,000',     salonCount: '~450 licensed salons', languages: ['Arabic'], paymentMethods: ['mada', 'Apple Pay', 'Card'], peakHours: '4 PM – 11 PM', context: 'Conservative heartland city; ladies salons operate with strict privacy requirements and exit-only rear doors.', priceTier: 'mid' },
  { slug: 'khamis-mushait',    city: 'Khamis Mushait',  country: 'SA', countryName: 'Saudi Arabia', region: 'Asir',           currency: 'SAR', currencySymbol: 'SAR', population: '520,000',     salonCount: '~380 licensed salons', languages: ['Arabic'], paymentMethods: ['mada', 'Apple Pay', 'Card'], peakHours: '4 PM – 11 PM', context: 'Air-base city adjacent to Abha; steady military + local family demand.', priceTier: 'mid' },
  { slug: 'hail',              city: 'Hail',            country: 'SA', countryName: 'Saudi Arabia', region: 'Hail',           currency: 'SAR', currencySymbol: 'SAR', population: '410,000',     salonCount: '~320 licensed salons', languages: ['Arabic'], paymentMethods: ['mada', 'Apple Pay', 'Card'], peakHours: '4 PM – 11 PM', context: 'Northern regional capital; wedding-season demand runs long across tribes and villages.', priceTier: 'mid' },
  { slug: 'hafar-al-batin',    city: 'Hafar Al-Batin',  country: 'SA', countryName: 'Saudi Arabia', region: 'Eastern Province',currency: 'SAR', currencySymbol: 'SAR', population: '380,000',     salonCount: '~300 licensed salons', languages: ['Arabic'], paymentMethods: ['mada', 'Apple Pay', 'Card'], peakHours: '4 PM – 11 PM', context: 'Strategic border city with a local-family-anchored salon base and Kuwaiti-cross-border demand.', priceTier: 'mid' },
  { slug: 'jubail',            city: 'Jubail',          country: 'SA', countryName: 'Saudi Arabia', region: 'Eastern Province',currency: 'SAR', currencySymbol: 'SAR', population: '380,000',     salonCount: '~280 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['mada', 'Apple Pay', 'Card'], peakHours: '4 PM – 11 PM', context: 'Industrial city with heavy expat contractor presence and compound-adjacent premium salons.', priceTier: 'mid' },
  { slug: 'najran',            city: 'Najran',          country: 'SA', countryName: 'Saudi Arabia', region: 'Najran',         currency: 'SAR', currencySymbol: 'SAR', population: '380,000',     salonCount: '~270 licensed salons', languages: ['Arabic'], paymentMethods: ['mada', 'Apple Pay', 'Card'], peakHours: '4 PM – 11 PM', context: 'Southern regional capital near the Yemen border; traditional salons with seasonal tribal wedding peaks.', priceTier: 'mid' },
  // Qatar — 4
  { slug: 'doha',              city: 'Doha',            country: 'QA', countryName: 'Qatar',        region: 'Doha',           currency: 'QAR', currencySymbol: 'QAR', population: '2.4 million', salonCount: '~2,200 licensed salons', languages: ['Arabic', 'English', 'Urdu'], paymentMethods: ['Apple Pay', 'Card', 'NFC'], peakHours: '3 PM – 12 AM', context: 'Compact city-state with tight salon licensing; subcontinental-stylist-led ladies salons dominate, plus hotel-attached spas for the premium tier.', priceTier: 'premium' },
  { slug: 'al-wakrah',         city: 'Al Wakrah',       country: 'QA', countryName: 'Qatar',        region: 'Al Wakrah',      currency: 'QAR', currencySymbol: 'QAR', population: '350,000',     salonCount: '~280 licensed salons', languages: ['Arabic', 'English', 'Urdu'], paymentMethods: ['Apple Pay', 'Card', 'NFC'], peakHours: '3 PM – 11 PM', context: 'Doha-south suburb with rapid new-resident growth; salons benefit from short-commute preference.', priceTier: 'premium' },
  { slug: 'al-rayyan',         city: 'Al Rayyan',       country: 'QA', countryName: 'Qatar',        region: 'Al Rayyan',      currency: 'QAR', currencySymbol: 'QAR', population: '700,000',     salonCount: '~600 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['Apple Pay', 'Card', 'NFC'], peakHours: '3 PM – 11 PM', context: 'Western Doha; Qatari-family heartland with conservative ladies-salon norms.', priceTier: 'premium' },
  { slug: 'al-khor',           city: 'Al Khor',         country: 'QA', countryName: 'Qatar',        region: 'Al Khor',        currency: 'QAR', currencySymbol: 'QAR', population: '220,000',     salonCount: '~170 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['Apple Pay', 'Card', 'NFC'], peakHours: '3 PM – 11 PM', context: 'Northern industrial + family city; LNG-community salons thrive on contractor payroll cycles.', priceTier: 'mid' },
  // Kuwait — 4
  { slug: 'kuwait-city',       city: 'Kuwait City',     country: 'KW', countryName: 'Kuwait',       region: 'Al Asimah',      currency: 'KWD', currencySymbol: 'KWD', population: '2.4 million', salonCount: '~2,000 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['KNET', 'Apple Pay', 'Card'], peakHours: '5 PM – 1 AM', context: 'Capital metro; KNET network drives most card volume, and Kuwaiti-female salon ownership grows steadily.', priceTier: 'premium' },
  { slug: 'al-ahmadi',         city: 'Al Ahmadi',       country: 'KW', countryName: 'Kuwait',       region: 'Al Ahmadi',      currency: 'KWD', currencySymbol: 'KWD', population: '740,000',     salonCount: '~620 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['KNET', 'Apple Pay', 'Card'], peakHours: '5 PM – 12 AM', context: 'Oil-belt governorate; mix of premium salons in Fintas and value-tier shops in Abu Halifa.', priceTier: 'mid' },
  { slug: 'hawalli',           city: 'Hawalli',         country: 'KW', countryName: 'Kuwait',       region: 'Hawalli',        currency: 'KWD', currencySymbol: 'KWD', population: '990,000',     salonCount: '~800 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['KNET', 'Apple Pay', 'Card'], peakHours: '5 PM – 1 AM', context: 'Expat-heavy governorate with a dense Levantine + subcontinental salon mix.', priceTier: 'mid' },
  { slug: 'salwa',             city: 'Salwa',           country: 'KW', countryName: 'Kuwait',       region: 'Mubarak Al-Kabeer', currency: 'KWD', currencySymbol: 'KWD', population: '130,000',   salonCount: '~130 licensed salons', languages: ['Arabic'], paymentMethods: ['KNET', 'Apple Pay', 'Card'], peakHours: '5 PM – 12 AM', context: 'Residential district with a Kuwaiti-family-first salon scene and wedding-season peaks.', priceTier: 'premium' },
  // Bahrain — 3
  { slug: 'manama',            city: 'Manama',          country: 'BH', countryName: 'Bahrain',      region: 'Capital',        currency: 'BHD', currencySymbol: 'BHD', population: '160,000',     salonCount: '~700 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['BenefitPay', 'Apple Pay', 'Card'], peakHours: '5 PM – 12 AM', context: 'Compact capital with an outsized salon count per capita; weekend GCC-tourism spikes drive Thursday\u2013Saturday volume.', priceTier: 'premium' },
  { slug: 'muharraq',          city: 'Muharraq',        country: 'BH', countryName: 'Bahrain',      region: 'Muharraq',       currency: 'BHD', currencySymbol: 'BHD', population: '180,000',     salonCount: '~280 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['BenefitPay', 'Apple Pay', 'Card'], peakHours: '5 PM – 11 PM', context: 'Old Bahraini cultural heartland; traditional Khaleeji bridal rituals keep ladies salons busy.', priceTier: 'mid' },
  { slug: 'riffa',             city: 'Riffa',           country: 'BH', countryName: 'Bahrain',      region: 'Southern',       currency: 'BHD', currencySymbol: 'BHD', population: '120,000',     salonCount: '~200 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['BenefitPay', 'Apple Pay', 'Card'], peakHours: '5 PM – 11 PM', context: 'Royal-neighbourhood city; high-end ladies salons cater to old-guard Bahraini families.', priceTier: 'premium' },
  // Oman — 5
  { slug: 'muscat',            city: 'Muscat',          country: 'OM', countryName: 'Oman',         region: 'Muscat',         currency: 'OMR', currencySymbol: 'OMR', population: '1.6 million', salonCount: '~1,200 licensed salons', languages: ['Arabic', 'English', 'Urdu'], paymentMethods: ['Apple Pay', 'Card', 'Cash'], peakHours: '4 PM – 11 PM', context: 'Coastal capital with a conservative licensing regime; ladies salons operate under strict privacy rules.', priceTier: 'premium' },
  { slug: 'salalah',           city: 'Salalah',         country: 'OM', countryName: 'Oman',         region: 'Dhofar',         currency: 'OMR', currencySymbol: 'OMR', population: '330,000',     salonCount: '~280 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['Apple Pay', 'Card', 'Cash'], peakHours: '4 PM – 11 PM', context: 'Khareef-monsoon tourism peaks in July\u2013September produce salon-booking surges that dwarf normal months.', priceTier: 'mid' },
  { slug: 'sohar',             city: 'Sohar',           country: 'OM', countryName: 'Oman',         region: 'Al Batinah North',currency: 'OMR', currencySymbol: 'OMR', population: '160,000',     salonCount: '~130 licensed salons', languages: ['Arabic', 'English'], paymentMethods: ['Apple Pay', 'Card', 'Cash'], peakHours: '4 PM – 10 PM', context: 'Industrial free-zone port; contractor-driven expat demand plus local Omani families.', priceTier: 'mid' },
  { slug: 'nizwa',             city: 'Nizwa',           country: 'OM', countryName: 'Oman',         region: 'Ad Dakhiliyah',  currency: 'OMR', currencySymbol: 'OMR', population: '110,000',     salonCount: '~80 licensed salons', languages: ['Arabic'], paymentMethods: ['Card', 'Cash'], peakHours: '4 PM – 9 PM', context: 'Interior heritage city; modest but steady salon demand with wedding-season bumps.', priceTier: 'mid' },
  { slug: 'sur',               city: 'Sur',             country: 'OM', countryName: 'Oman',         region: 'Ash Sharqiyah South',currency: 'OMR', currencySymbol: 'OMR', population: '80,000',      salonCount: '~60 licensed salons', languages: ['Arabic'], paymentMethods: ['Card', 'Cash'], peakHours: '4 PM – 9 PM', context: 'Historic dhow-building coastal town; small but loyal salon ecosystem.', priceTier: 'mid' },
];

// Gulf cities removed from routing + sitemap on 2026-04-21 to focus SEO on
// Pakistan only. GULF_CITIES data preserved above for potential future
// expansion; it is exported but intentionally not wired into ALL_CITIES.
export const ALL_CITIES: CityRecord[] = [...PAKISTAN_CITIES];

export function getCity(slug: string): CityRecord | null {
  return ALL_CITIES.find((c) => c.slug === slug) ?? null;
}
