'use server';

import { createServerClient } from '@/lib/supabase';
import { verifySession } from './auth';
import { sendEmail } from '@/lib/email-sender';
import type { SalesAgent } from '@/types/sales';

async function requireSuperAdmin() {
  const session = await verifySession();
  if (!session || session.role !== 'super_admin') {
    throw new Error('Unauthorized');
  }
  return session;
}

export interface CreateAgentInput {
  email: string;
  name: string;
  phone: string;
  city: string | null;
  firstSalePct: number;
  renewalPct: number;
  demoPassword: string;
}

function validatePct(n: number): string | null {
  if (!Number.isFinite(n) || n < 0 || n > 100) return 'Percent must be between 0 and 100';
  return null;
}

export async function createSalesAgent(
  input: CreateAgentInput,
): Promise<{ data: (SalesAgent & { demoEmail: string }) | null; error: string | null }> {
  await requireSuperAdmin();

  const pctErr = validatePct(input.firstSalePct) ?? validatePct(input.renewalPct);
  if (pctErr) return { data: null, error: pctErr };
  if (!input.email || !input.name) return { data: null, error: 'Email and name required' };
  if (!input.phone?.trim()) return { data: null, error: 'Phone is required' };
  if (!input.demoPassword || input.demoPassword.length < 8) {
    return { data: null, error: 'Demo password must be at least 8 characters' };
  }

  const supabase = createServerClient();

  // 1. Create real auth user with a random password (they reset via email link).
  const tmpPassword = crypto.randomUUID() + 'A1!';
  const { data: authData, error: authErr } = await supabase.auth.admin.createUser({
    email: input.email,
    password: tmpPassword,
    email_confirm: true,
  });
  if (authErr || !authData.user) {
    return { data: null, error: authErr?.message ?? 'Failed to create auth user' };
  }

  // 2. Insert real sales_agents row (code auto-generated by DB default).
  const { data, error } = await supabase
    .from('sales_agents')
    .insert({
      user_id: authData.user.id,
      name: input.name,
      phone: input.phone.trim(),
      city: input.city,
      first_sale_pct: input.firstSalePct,
      renewal_pct: input.renewalPct,
    })
    .select()
    .single();

  if (error) {
    // Clean up orphaned auth user
    await supabase.auth.admin.deleteUser(authData.user.id).catch(() => {});
    return { data: null, error: error.message };
  }

  // 3. Create the paired demo identity. Demo email follows the convention
  //    <code>-demo@icut.pk so prospects can guess it from the agent's flyer.
  const demoEmail = `${data.code.toLowerCase()}-demo@icut.pk`;
  const { data: demoAuthData, error: demoAuthErr } = await supabase.auth.admin.createUser({
    email: demoEmail,
    password: input.demoPassword,
    email_confirm: true,
  });
  if (demoAuthErr || !demoAuthData.user) {
    // Roll back the real agent + auth user so we don't have a half-created pair.
    try { await supabase.from('sales_agents').delete().eq('id', data.id); } catch { /* swallow */ }
    await supabase.auth.admin.deleteUser(authData.user.id).catch(() => {});
    return { data: null, error: `Demo account creation failed: ${demoAuthErr?.message ?? 'unknown'}` };
  }

  const { error: demoAgentErr } = await supabase
    .from('sales_agents')
    .insert({
      user_id: demoAuthData.user.id,
      name: `${input.name} (Demo)`,
      phone: input.phone.trim(),
      city: input.city,
      first_sale_pct: input.firstSalePct,
      renewal_pct: input.renewalPct,
      code: `${data.code}-D`,
      is_demo: true,
      parent_agent_id: data.id,
    });
  if (demoAgentErr) {
    await supabase.auth.admin.deleteUser(demoAuthData.user.id).catch(() => {});
    try { await supabase.from('sales_agents').delete().eq('id', data.id); } catch { /* swallow */ }
    await supabase.auth.admin.deleteUser(authData.user.id).catch(() => {});
    return { data: null, error: `Demo agent row failed: ${demoAgentErr.message}` };
  }

  // 3. Send password-reset link so agent can set their own password
  try {
    const origin = process.env.NEXT_PUBLIC_APP_URL || 'https://icut.pk';
    const { data: linkData } = await supabase.auth.admin.generateLink({
      type: 'recovery',
      email: input.email,
      options: { redirectTo: `${origin}/reset-password` },
    });
    const link = linkData?.properties?.action_link;
    if (link) {
      await sendEmail(
        input.email,
        'iCut — Your sales agent account',
        `<p>Hi ${input.name},</p>
         <p>You've been added as a sales agent on iCut. Set your password here:</p>
         <p><a href="${link}">Set password</a></p>
         <p>Then log in at ${origin}/login.</p>`,
      );
    }
  } catch {
    // Non-critical — superadmin can resend via reset flow
  }

  return { data: { ...(data as SalesAgent), demoEmail }, error: null };
}

/**
 * Super-admin only: reset the demo password for an agent's paired demo identity.
 * Looks up the demo child by parent_agent_id, then updates the auth user via
 * the admin API.
 */
export async function setDemoPassword(parentAgentId: string, newPassword: string): Promise<{ error: string | null }> {
  await requireSuperAdmin();
  if (!newPassword || newPassword.length < 8) {
    return { error: 'Demo password must be at least 8 characters' };
  }
  const supabase = createServerClient();
  const { data: demo } = await supabase
    .from('sales_agents')
    .select('user_id')
    .eq('parent_agent_id', parentAgentId)
    .eq('is_demo', true)
    .maybeSingle();
  if (!demo) return { error: 'Demo identity not found' };
  const { error } = await supabase.auth.admin.updateUserById(demo.user_id, { password: newPassword });
  return { error: error?.message ?? null };
}

/**
 * Super-admin only: look up an agent's demo email + password-reset link.
 * Used by /admin/agents/[id] to surface demo creds.
 */
export async function getDemoCredentials(parentAgentId: string): Promise<{
  data: { email: string } | null;
  error: string | null;
}> {
  await requireSuperAdmin();
  const supabase = createServerClient();
  const { data: demo } = await supabase
    .from('sales_agents')
    .select('user_id')
    .eq('parent_agent_id', parentAgentId)
    .eq('is_demo', true)
    .maybeSingle();
  if (!demo) return { data: null, error: 'Demo identity not found' };
  const { data: authUser } = await supabase.auth.admin.getUserById(demo.user_id);
  if (!authUser?.user?.email) return { data: null, error: 'Demo auth user missing' };
  return { data: { email: authUser.user.email }, error: null };
}

export async function listSalesAgents(): Promise<{ data: SalesAgent[]; error: string | null }> {
  await requireSuperAdmin();
  const supabase = createServerClient();
  // Demo identities live in the same table — hide them from the agents list
  // so super admin sees one row per real agent. Demo creds for each are
  // surfaced on the agent detail page.
  const { data, error } = await supabase
    .from('sales_agents')
    .select('*')
    .eq('is_demo', false)
    .order('created_at', { ascending: false });
  if (error) return { data: [], error: error.message };
  return { data: (data || []) as SalesAgent[], error: null };
}

export async function getSalesAgent(id: string): Promise<{ data: SalesAgent | null; error: string | null }> {
  await requireSuperAdmin();
  const supabase = createServerClient();
  const { data, error } = await supabase
    .from('sales_agents')
    .select('*')
    .eq('id', id)
    .maybeSingle();
  if (error) return { data: null, error: error.message };
  return { data: (data as SalesAgent) || null, error: null };
}

export async function updateAgentRates(
  id: string,
  rates: { firstSalePct: number; renewalPct: number },
): Promise<{ error: string | null }> {
  await requireSuperAdmin();
  const pctErr = validatePct(rates.firstSalePct) ?? validatePct(rates.renewalPct);
  if (pctErr) return { error: pctErr };
  const supabase = createServerClient();
  const { error } = await supabase
    .from('sales_agents')
    .update({ first_sale_pct: rates.firstSalePct, renewal_pct: rates.renewalPct })
    .eq('id', id);
  return { error: error?.message ?? null };
}

export async function setAgentActive(
  id: string,
  active: boolean,
): Promise<{ error: string | null }> {
  await requireSuperAdmin();
  const supabase = createServerClient();
  const ts = active ? null : new Date().toISOString();

  // Update the requested agent first.
  const { error } = await supabase
    .from('sales_agents')
    .update({ active, deactivated_at: ts })
    .eq('id', id);
  if (error) return { error: error.message };

  // Cascade to the paired demo identity. FK ON DELETE CASCADE only handles
  // hard deletes; for active flips we mirror manually so deactivating a real
  // agent also kills their demo login.
  const { error: demoErr } = await supabase
    .from('sales_agents')
    .update({ active, deactivated_at: ts })
    .eq('parent_agent_id', id);
  if (demoErr) return { error: `Cascade to demo failed: ${demoErr.message}` };

  return { error: null };
}

export async function updateAgentProfile(
  id: string,
  fields: { name?: string; phone?: string; city?: string | null },
): Promise<{ error: string | null }> {
  await requireSuperAdmin();
  if (fields.phone !== undefined && !fields.phone.trim()) {
    return { error: 'Phone cannot be empty' };
  }
  const supabase = createServerClient();
  const { error } = await supabase.from('sales_agents').update(fields).eq('id', id);
  return { error: error?.message ?? null };
}

export async function updateOwnAgentProfile(
  fields: { name: string; phone: string },
): Promise<{ error: string | null }> {
  const session = await verifySession();
  if (!session || session.role !== 'sales_agent' || !session.agentId) {
    throw new Error('Unauthorized');
  }
  if (!fields.phone?.trim()) return { error: 'Phone is required' };
  const supabase = createServerClient();
  const { error } = await supabase
    .from('sales_agents')
    .update({ name: fields.name, phone: fields.phone.trim() })
    .eq('id', session.agentId);
  return { error: error?.message ?? null };
}

export async function getMyAgentProfile(): Promise<{ data: SalesAgent | null; error: string | null }> {
  const session = await verifySession();
  if (!session || session.role !== 'sales_agent' || !session.agentId) throw new Error('Unauthorized');
  const supabase = createServerClient();
  const { data, error } = await supabase
    .from('sales_agents')
    .select('*')
    .eq('id', session.agentId)
    .maybeSingle();
  if (error) return { data: null, error: error.message };
  return { data: (data as SalesAgent) || null, error: null };
}
